name: Build and Deploy

on:
  push:
    # GeiChan Repo
    branches: [ v2 ]
    # AilveGei Repo
#    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: 缓存依赖
        uses: actions/cache@v2.1.1
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      # GeiChan Repo
      - name: vuepress 部署
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: GeiChan/geichan.github.io
          TARGET_BRANCH: main
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist

      # AilveGei Repo
#      - name: vuepress 部署
#        uses: jenkey2011/vuepress-deploy@master
#        env:
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#          TARGET_REPO: AilveGei/ailvegei.github.io
#          TARGET_BRANCH: main
#          BUILD_SCRIPT: yarn && yarn docs:build
#          BUILD_DIR: docs/.vuepress/dist